---
title: Kies een emoji
hero_image: images/banner.png
description: Kies een emoji voor je project.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Kies een emoji
