title: Choose an emoji
hero_image: images/banner.png
description: Choose an emoji for your project.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Choose an emoji
