---
title: Escolha um emoji
hero_image: images/banner.png
description: Escolha um emoji para o seu projeto.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Escolha um emoji
