title: Wybierz emoji
hero_image: images/banner.png
description: Wybierz emoji do swojego projektu.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Wybierz emoji
