---
title: Επίλεξε ένα emoji
hero_image: images/banner.png
description: Επίλεξε ένα emoji που να ταιριάζει στο έργο σου.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Επίλεξε ένα emoji
