title: Choisir un emoji
hero_image: images/banner.png
description: Choisir un emoji pour ton projet.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Choisir un emoji
