---
title: Scegli un'emoji
hero_image: images/banner.png
description: Scegli un'emoji per il tuo progetto.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Scegli un'emoji
